# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START cloudbuild_basic_config]

substitutions:
  # XXX: set image and tag
  _IMAGE_NAME: gctapp/web
  _PROJECT_ID: toki-take-home-2023
  # requires string, not float
  _GIT_SHA: version-1  # updating this may not bust the cache because we --cache-from multiple tags, you'd need to comment out the --cache-from or use --no-cache for a proper cache bust behaviour

steps:

# Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', '.docker/images/web', '-t', 
           'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_GITHUB_SHA}', 
           '.']

# Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_GITHUB_SHA}']