##
## Example: https://github.com/HariSekhon/Templates/blob/master/cloudbuild.yaml
##

substitutions:
  _IMAGE_NAME: gctapp/web
  _PROJECT_ID: toki-take-home-2023
  _GITHUB_SHA: version-1  # updating this may not bust the cache because we --cache-from multiple tags, you'd need to comment out the --cache-from or use --no-cache for a proper cache bust behaviour

steps:

# Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', '.docker/images/web/Dockerfile', '-t', 
           'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_GITHUB_SHA}', 
           '.']

# Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_GITHUB_SHA}']