version: '3.7'

services:
  web:
    platform: linux/amd64
    image: gctapp/web
    container_name: gctapp-web
    ports:
      - 18080:8080
    build:
      context: .
      dockerfile: ./.docker/images/web/Dockerfile
      # target: gctapp-web-dev
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ENV=LOCALDEV

  api:
    image: gctapp/api
    container_name: gctapp-api
    build:
      context: .
      dockerfile: ./.docker/images/api/Dockerfile
      target: gctapp-api-dev
    ports:
      - 28080:7000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ENV=LOCALDEV
      - PORT=7000
      - REDIS_CONNECTION_STRING=redis://gctapp-redis:6379

  redis:
    image: redislabs/redistimeseries
    container_name: gctapp-redis
    ports:
      - 6379:6379
    extra_hosts:
      - "host.docker.internal:host-gateway"