name: Google Cloud Run Deploy
# https://github.com/google-github-actions/setup-gcloud
on:
  push:
    branches:
      - dev
    paths:
      - '.docker/images/api/**/*'
      - 'packages/api/**/*.ts'
      - 'packages/api/**/*.json'
      - 'packages/core/**/*.ts'
      - 'packages/core/**/*.json'
      - '.github/workflows/wf-gctappapi-dev.yml'

env:
  PROJECT_ID: toki-take-home-2023
  RUN_REGION: europe-west3
  IMAGE_NAME: gctapp/api
  SERVICE_NAME: gctapp-api
  PORT: 8080

jobs:
  # build:
  #   name: Build Gct Api
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@main

  #     - name: Setup Node.js (NPM)
  #       uses: actions/setup-node@master
  #       with:
  #         node-version: '18.x'

  #     - name: Use cached node_modules
  #       uses: actions/cache@master
  #       with:
  #         path: node_modules
  #         key: nodeModules-${{ hashFiles('**/package-lock.json') }}
  #         restore-keys: |
  #           nodeModules-
  #     - name: Install dependencies
  #       run: npm install -w @gctapp/api && npm install -g typescript
  #       env:
  #         CI: true

  #     - name: Build Development
  #       run: |-
  #         tsc --build packages/core packages/api/ --verbose \
  #         && mkdir packages/api/build \
  #         && cp -r --preserve=links node_modules packages/api/dist packages/api/build/ \
  #         && rm -fr packages/api/build/node_modules/@gctapp/* \
  #         && cp -r -L node_modules/@gctapp/core packages/api/build/node_modules/@gctapp/

  #     - name: Archive Production Artifact
  #       uses: actions/upload-artifact@main
  #       with:
  #         name: build
  #         path: packages/api/build

  deploy-gcr:
    name: Deploy to GCR
    # needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      # - name: Download Artifact
      #   uses: actions/download-artifact@main
      #   with:
      #     name: build
      #     path: packages/api/build

      - name: Setup GCloud Auth
        id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCR_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1

      # Build and push image to Google Container Registry
      - name: Build & Push
      
      #using gcloud cli directly
      #   run: |-
      #     gcloud builds submit \
      #       --quiet \
      #       --config ".github/cb-gctappweb-dev.yaml"
      #       --substitutions="_PROJECT_ID=$PROJECT_ID,_IMAGE_NAME=$IMAGE_NAME,_SERVICE_NAME=$SERVICE_NAME,_GITHUB_SHA=$GITHUB_SHA"
      #   working-directory: .
      #   env:
      #     PROJECT_ID: toki-take-home-2023
      #     RUN_REGION: europe-west3
      #     IMAGE_NAME: gctapp/web
      #     SERVICE_NAME: gctapp-web

      #using kaniko
        # since not using gcloudd cli here, kaniko needs credentials 
        #
        # 1) passing -e GOOGLE_APPLICATION_CREDENTIALS=/kaniko/config.json
        # 2) and also mounting the credentials into this path /kaniko/config.json

        # We could omit 1) and only mount credentials into this path, since it is the default
        # For clarity we do both 1) and 2)

        # TODO how we proceed? Are we buiding inside docker or we stick with building above, then uploading artifact then, donloading it and using it
        # Which is faster: caching node_modules like above, or caching via kaniko?
        # TODO test them both
        run: |-
          docker run \
          -e GOOGLE_APPLICATION_CREDENTIALS=/kaniko/config.json \
          -v $GOOGLE_APPLICATION_CREDENTIALS:/kaniko/config.json \
          -v ${PWD}:/workspace \
          gcr.io/kaniko-project/executor:latest \
          --dockerfile /workspace/.docker/images/api/Dockerfile \
          --destination "gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA" \
          --context dir:///workspace/
        working-directory: .
        
      # Deploy image to Cloud Run
      - name: Deploy GCR
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --image "gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA" \
            --max-instances=1 \
            --platform managed \
            --region $RUN_REGION \
            --vpc-connector gctapp-ew3 \
            --allow-unauthenticated \
            --set-env-vars "REDIS_CONNECTION_STRING=redis://redis-18153.c302.asia-northeast1-1.gce.cloud.redislabs.com:18153,GCT_ENV=DEV" \
            --set-secrets=REDIS_PWD=secret-redis-cloud-db-pwd:1 \
            --port=$PORT