name: Google Cloud Run Deploy
# https://github.com/google-github-actions/setup-gcloud
on:
  push:
    branches:
      - dev
    paths:
      - '.docker/images/redis/**/*'
      - '.github/workflows/wf-gctappredis-dev.yml'

env:
  PROJECT_ID: toki-take-home-2023
  RUN_REGION: europe-west3
  IMAGE_NAME: gctapp/redis
  SERVICE_NAME: gctapp-redis

jobs:
  
  deploy-gcr:
    name: Deploy to GCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Setup GCloud Auth
        id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCR_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1

      - name: Build & Push

      #using kaniko
        # since not using gcloudd cli here, kaniko needs credentials 
        #
        # 1) passing -e GOOGLE_APPLICATION_CREDENTIALS=/kaniko/config.json
        # 2) and also mounting the credentials into this path /kaniko/config.json

        # We could omit 1) and only mount credentials into this path, since it is the default
        # For clarity we do both 1) and 2)

        # TODO how we proceed? Are we buiding inside docker or we stick with building above, then uploading artifact then, donloading it and using it
        # Which is faster: caching node_modules like above, or caching via kaniko?
        # TODO test them both
        run: |-
          docker run \
          -e GOOGLE_APPLICATION_CREDENTIALS=/kaniko/config.json \
          -v $GOOGLE_APPLICATION_CREDENTIALS:/kaniko/config.json \
          -v ${PWD}:/workspace \
          gcr.io/kaniko-project/executor:latest \
          --dockerfile /workspace/.docker/images/redis/Dockerfile \
          --destination "gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA" \
          --context dir:///workspace/
        working-directory: .
        
      # Deploy image to Cloud Run
      - name: Deploy GCR
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --ingress=internal \
            --max-instances=1 \
            --region "$RUN_REGION" \
            --image "gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated